language: generic
sudo: false
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-git-snapshot-travis
before-install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask --debug
  # temporary fix for the ert+duration reporter, when compiled gives
  # "Invalid time specification"
  - find . -name 'ert-runner-reporter-ert+duration.elc' -delete
script:
- cask exec ert-runner --reporter ert+duration
